swift_version: 5.0
type_name:
  allowed_symbols: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"
# Line length
line_length:
  warning: 120
  error: 500

opt_in_rules:
     - indentation_width
     - operator_usage_whitespace
